import type { ContactData } from "@piya/shared/types";

const now = new Date("2026-06-24T09:00:00.000Z").getTime();

const contacts: ContactData[] = [
  {
    id: "ct_001",
    createdAt: now - 1000 * 60 * 60 * 24 * 120,
    updatedAt: now - 1000 * 60 * 60 * 2,
    userId: "usr_001",
    code: "YIN-AMARA-001",
    createdBy: "admin_001",
    businessId: "biz_northstar",
    name: "Amara Okafor",
    profileImageUrl: null,
    email: "amara@example.com",
    phoneNumber: "+234 801 230 9921",
    countryCode: "NG",
    address: {
      address: "18 Admiralty Way",
      city: "Lekki",
      state: "Lagos",
      country: "Nigeria",
      postalCode: "105102",
    },
    badge: {
      type: "gold",
      points: 4820,
      updatedAt: now - 1000 * 60 * 60 * 24 * 7,
    },
    dob: "1991-04-18",
    bmd: "04-18",
    preference: {
      unsubscribedEmailTypes: ["weekly_digest"],
      smsEnabled: true,
      emailEnabled: true,
      whatsappEnabled: true,
    },
    status: "active",
    lastInteractionAt: now - 1000 * 60 * 45,
    anniversary: "2024-02-14",
    tags: ["high value", "vip"],
    counts: {
      lifetimeValue: 1268000,
      totalOrders: 28,
      messagesSentCount: 42,
      messagesRepliedCount: 19,
    },
    metadata: null,
  },
  {
    id: "ct_002",
    createdAt: now - 1000 * 60 * 60 * 24 * 9,
    updatedAt: now - 1000 * 60 * 60 * 26,
    userId: "usr_002",
    code: "YIN-TUNDE-002",
    createdBy: "admin_001",
    businessId: "biz_urbanmart",
    name: "Tunde Balogun",
    profileImageUrl: null,
    email: "tunde@example.com",
    phoneNumber: "+234 809 441 1820",
    countryCode: "NG",
    address: {
      address: "22 Awolowo Road",
      city: "Ikoyi",
      state: "Lagos",
      country: "Nigeria",
      postalCode: "101233",
    },
    badge: {
      type: "bronze",
      points: 680,
      updatedAt: now - 1000 * 60 * 60 * 24,
    },
    dob: null,
    bmd: null,
    preference: {
      unsubscribedEmailTypes: [],
      smsEnabled: true,
      emailEnabled: true,
      whatsappEnabled: false,
    },
    status: "lead",
    lastInteractionAt: now - 1000 * 60 * 60 * 24,
    anniversary: null,
    tags: ["new lead"],
    counts: {
      lifetimeValue: 94000,
      totalOrders: 2,
      messagesSentCount: 5,
      messagesRepliedCount: 1,
    },
    metadata: null,
  },
  {
    id: "ct_003",
    createdAt: now - 1000 * 60 * 60 * 24 * 210,
    updatedAt: now - 1000 * 60 * 60 * 24 * 4,
    userId: "usr_003",
    code: "YIN-MAYA-003",
    createdBy: "admin_002",
    businessId: "biz_studio_atlas",
    name: "Maya Chen",
    profileImageUrl: null,
    email: "maya@example.com",
    phoneNumber: "+1 415 209 7744",
    countryCode: "US",
    address: {
      address: "190 King Street",
      city: "San Francisco",
      state: "California",
      country: "United States",
      postalCode: "94107",
    },
    badge: {
      type: "silver",
      points: 2360,
      updatedAt: now - 1000 * 60 * 60 * 24 * 22,
    },
    dob: "1988-11-02",
    bmd: "11-02",
    preference: {
      unsubscribedEmailTypes: ["product_updates"],
      smsEnabled: false,
      emailEnabled: true,
      whatsappEnabled: false,
    },
    status: "active",
    lastInteractionAt: now - 1000 * 60 * 60 * 24 * 4,
    anniversary: "2023-10-05",
    tags: ["email only"],
    counts: {
      lifetimeValue: 612000,
      totalOrders: 11,
      messagesSentCount: 16,
      messagesRepliedCount: 7,
    },
    metadata: null,
  },
  {
    id: "ct_004",
    createdAt: now - 1000 * 60 * 60 * 24 * 320,
    updatedAt: now - 1000 * 60 * 60 * 24 * 12,
    userId: "usr_004",
    code: "YIN-DANIEL-004",
    createdBy: "admin_002",
    businessId: "biz_clearpath",
    name: "Daniel Mensah",
    profileImageUrl: null,
    email: "daniel@example.com",
    phoneNumber: "+233 24 778 1091",
    countryCode: "GH",
    address: {
      address: "14 Independence Avenue",
      city: "Accra",
      state: "Greater Accra",
      country: "Ghana",
      postalCode: "GA-184",
    },
    badge: {
      type: "regular",
      points: 120,
      updatedAt: now - 1000 * 60 * 60 * 24 * 35,
    },
    dob: null,
    bmd: null,
    preference: {
      unsubscribedEmailTypes: ["marketing"],
      smsEnabled: false,
      emailEnabled: false,
      whatsappEnabled: true,
    },
    status: "inactive",
    lastInteractionAt: now - 1000 * 60 * 60 * 24 * 12,
    anniversary: null,
    tags: ["at risk"],
    counts: {
      lifetimeValue: 184000,
      totalOrders: 4,
      messagesSentCount: 21,
      messagesRepliedCount: 3,
    },
    metadata: null,
  },
];

export function getContacts() {
  return contacts;
}
