export type BusinessType = "storefront" | "logistics" | "services";

export type Business = {
  id: string;
  name: string;
  type: BusinessType;
};

export type {
  AvailabilityData,
  AvailabilityInterval,
  AvailabilityIntervalType,
  AvailabilityStatusType,
  AvailableEventSlot,
  BookingData,
  BookingParticipant,
  BookingParticipantRoleType,
  BookingParticipantStatusType,
  BookingParticipantType,
  BookingStatusType,
  BusinessBranding,
  BusinessCategoryTypes,
  BusinessData,
  BusinessStatusType,
  CampaignData,
  CampaignReward,
  CampaignRewardMetadata,
  CampaignRules,
  CampaignStatusType,
  CampaignType,
  ChannelProviderStatusType,
  ChannelSettingsData,
  ChatChannelType,
  ChatData,
  ChatProfileRoleType,
  Contact,
  ContactBadge,
  ContactBadgeType,
  ContactCounts,
  ContactData,
  ContactPreference,
  ContactStatus,
  ContactStatusType,
  DateAt,
  DeliveryData,
  DeliveryModel,
  DeliveryStatusType,
  DocumentStatusType,
  DomainData,
  DomainStatusType,
  DomainType,
  EmailChannelSettings,
  GeoPointData,
  IDType,
  LocationData,
  LocationDetailRequest,
  LocationPrediction,
  LocationSearchOptions,
  LocationServiceRequest,
  MemberData,
  MemberPermissionType,
  MemberRoleType,
  Message,
  MessageContent,
  MessageDeliveryStatusType,
  MessageDirectionType,
  MiniLocationData,
  MiniServiceData,
  MiniUserData,
  Providers,
  ServiceLocationData,
  SiteData,
  SiteSections,
  SiteSeo,
  SiteStatusType,
  SMSChannelSettings,
  SMSRegistrationStatusType,
  SMSSenderType,
  TimeAt,
  TimezoneData,
  UserBusinessData,
  UserData,
  UserGenderType,
  UserRoleType,
  UserSettingsData,
  VerificationData,
  WhatsAppChannelSettings,
} from "../models";

export type {
  DecodedBase64File,
  ImageContentType,
  UploadFileOptions,
} from "./storage";

export type {
  OTPDeliveryChannel,
  OTPRequestType,
  RequestEmailOTPParams,
  RequestOTPResult,
  RequestPhoneOTPParams,
  SendSMSParams,
  SendSMSResponse,
  VerifyAuthOTPParams,
  VerifyAuthOTPReason,
  VerifyAuthOTPResult,
} from "./auth";
