import type {
  ContactData,
  DiscountData,
  GiftData,
  OfferingData,
  OrderData,
} from "../models";
import type { CommunicationAdminData, CommunicationRecipient } from "../types";

const day = 1000 * 60 * 60 * 24;
const contactNow = new Date("2026-06-24T09:00:00.000Z").getTime();
const communicationNow = new Date("2026-06-24T09:00:00.000Z").getTime();
const orderNow = new Date("2026-06-24T10:30:00.000Z").getTime();

export const dummyCommunications: CommunicationAdminData[] = [
  {
    id: "comm_welcome_series",
    createdAt: communicationNow - day * 45,
    updatedAt: communicationNow - day * 2,
    name: "Welcome series",
    businessId: "biz_northstar",
    createdBy: "admin_001",
    isActive: true,
    status: "active",
    type: "onboarding",
    hasPendingBatch: true,
    lastExecutedAt: communicationNow - 1000 * 60 * 35,
    lastCursor: "ct_004",
    trigger: { type: "onboarding", schedule: null },
    targetAudience: {
      targetTags: ["new lead", "first order"],
      targetBadgeTypes: ["new", "bronze"],
    },
    stepsOrder: ["welcome_email", "welcome_whatsapp"],
    steps: {
      welcome_email: {
        channel: "email",
        delay: 0,
        identityId: "email_resend_default",
        message: {
          subject: "Welcome to Piya",
          body: "Hi {{firstName}}, your rewards profile is ready. Explore your perks and start earning today.",
        },
        ctas: [
          {
            label: "View rewards",
            url: "https://piya.store/rewards",
            type: "primary",
          },
        ],
        template: {
          name: "welcome_email",
          language: "en",
          providerTemplateId: "tmpl_welcome_001",
        },
      },
      welcome_whatsapp: {
        channel: "whatsapp",
        delay: 1440,
        identityId: "wa_cloud_main",
        message: {
          body: "Your welcome points are waiting. Reply HELP if you need anything.",
        },
        ctas: [],
        template: { name: "welcome_whatsapp_followup", language: "en" },
      },
    },
    stats: { recipients: 1248, delivered: 1196, failed: 18, pending: 34 },
  },
  {
    id: "comm_june_discount",
    createdAt: communicationNow - day * 12,
    updatedAt: communicationNow - day,
    name: "June discount alert",
    businessId: "biz_northstar",
    createdBy: "admin_001",
    isActive: true,
    status: "active",
    type: "discount_alert",
    hasPendingBatch: false,
    lastExecutedAt: communicationNow - day,
    lastCursor: null,
    trigger: {
      type: "discount_alert",
      schedule: {
        frequency: "once",
        dayOfWeek: 3,
        hour: 10,
        minute: 30,
        startDate: communicationNow + day * 2,
        timezone: "Africa/Lagos",
      },
    },
    targetAudience: {
      targetTags: ["vip", "high value"],
      targetBadgeTypes: ["gold", "platinum"],
    },
    stepsOrder: ["discount_sms"],
    steps: {
      discount_sms: {
        channel: "sms",
        delay: 0,
        identityId: "sms_link_mobility_ng",
        message: {
          body: "Piya App: Your VIP discount is live. Use code JUNE20 before Sunday.",
        },
        ctas: [],
        template: null,
      },
    },
    stats: { recipients: 428, delivered: 401, failed: 6, pending: 21 },
  },
  {
    id: "comm_winback",
    createdAt: communicationNow - day * 62,
    updatedAt: communicationNow - day * 8,
    name: "Win back inactive customers",
    businessId: "biz_northstar",
    createdBy: "admin_002",
    isActive: false,
    status: "paused",
    type: "win_back_inactive",
    hasPendingBatch: false,
    lastExecutedAt: communicationNow - day * 8,
    lastCursor: null,
    trigger: {
      type: "win_back_inactive",
      schedule: {
        frequency: "weekly",
        dayOfWeek: 1,
        hour: 9,
        minute: 0,
        startDate: communicationNow - day * 45,
        timezone: "Africa/Lagos",
      },
    },
    targetAudience: {
      targetTags: ["at risk"],
      targetBadgeTypes: ["bronze", "silver"],
    },
    stepsOrder: ["winback_email"],
    steps: {
      winback_email: {
        channel: "email",
        delay: 0,
        identityId: "email_resend_default",
        message: {
          subject: "We saved something for you",
          body: "Come back this week and unlock a loyalty reward on your next order.",
        },
        ctas: [
          {
            label: "Claim reward",
            url: "https://piya.store/offers/winback",
            type: "primary",
          },
        ],
        template: { name: "winback_offer", language: "en" },
      },
    },
    stats: { recipients: 812, delivered: 768, failed: 23, pending: 0 },
  },
];

export const dummyCommunicationRecipientsByCommunicationId: Record<
  string,
  CommunicationRecipient[]
> = {
  comm_welcome_series: [
    {
      id: "ct_001",
      name: "Amara Okafor",
      email: "amara@example.com",
      phoneNumber: "+234 801 230 9921",
      status: "delivered",
      channel: "email",
      lastActivityAt: communicationNow - 1000 * 60 * 35,
    },
    {
      id: "ct_002",
      name: "Tunde Balogun",
      email: "tunde@example.com",
      phoneNumber: "+234 809 441 1820",
      status: "pending",
      channel: "whatsapp",
      lastActivityAt: communicationNow - 1000 * 60 * 8,
    },
  ],
  comm_june_discount: [
    {
      id: "ct_003",
      name: "Maya Chen",
      email: "maya@example.com",
      phoneNumber: "+1 415 209 7744",
      status: "delivered",
      channel: "sms",
      lastActivityAt: communicationNow - day,
    },
  ],
  comm_winback: [
    {
      id: "ct_004",
      name: "Daniel Mensah",
      email: "daniel@example.com",
      phoneNumber: "+233 24 778 1091",
      status: "failed",
      channel: "email",
      lastActivityAt: communicationNow - day * 8,
    },
  ],
};

export const dummyContacts: ContactData[] = [
  {
    id: "ct_001",
    createdAt: contactNow - day * 120,
    updatedAt: contactNow - 1000 * 60 * 60 * 2,
    userId: "usr_001",
    code: "YIN-AMARA-001",
    createdBy: "admin_001",
    businessId: "biz_northstar",
    name: "Amara Okafor",
    profileImageUrl: null,
    email: "amara@example.com",
    phoneNumber: "+234 801 230 9921",
    countryCode: "NG",
    address: {
      address: "18 Admiralty Way",
      city: "Lekki",
      state: "Lagos",
      country: "Nigeria",
      postalCode: "105102",
    },
    badge: { badgeId: "gold", points: 4820, updatedAt: contactNow - day * 7 },
    dob: "1991-04-18",
    bmd: "04-18",
    preference: {
      unsubscribedEmailTypes: ["weekly_digest"],
      smsEnabled: true,
      emailEnabled: true,
      whatsappEnabled: true,
    },
    status: "active",
    lastInteractionAt: contactNow - 1000 * 60 * 45,
    anniversary: "2024-02-14",
    tags: ["high value", "vip"],
    counts: {
      lifetimeValue: 1268000,
      totalOrders: 28,
      messagesSentCount: 42,
      messagesRepliedCount: 19,
    },
    metadata: null,
  },
  {
    id: "ct_002",
    createdAt: contactNow - day * 9,
    updatedAt: contactNow - 1000 * 60 * 60 * 26,
    userId: "usr_002",
    code: "YIN-TUNDE-002",
    createdBy: "admin_001",
    businessId: "biz_urbanmart",
    name: "Tunde Balogun",
    profileImageUrl: null,
    email: "tunde@example.com",
    phoneNumber: "+234 809 441 1820",
    countryCode: "NG",
    address: {
      address: "22 Awolowo Road",
      city: "Ikoyi",
      state: "Lagos",
      country: "Nigeria",
      postalCode: "101233",
    },
    badge: { badgeId: "bronze", points: 680, updatedAt: contactNow - day },
    dob: null,
    bmd: null,
    preference: {
      unsubscribedEmailTypes: [],
      smsEnabled: true,
      emailEnabled: true,
      whatsappEnabled: false,
    },
    status: "lead",
    lastInteractionAt: contactNow - day,
    anniversary: null,
    tags: ["new lead"],
    counts: {
      lifetimeValue: 94000,
      totalOrders: 2,
      messagesSentCount: 5,
      messagesRepliedCount: 1,
    },
    metadata: null,
  },
  {
    id: "ct_003",
    createdAt: contactNow - day * 210,
    updatedAt: contactNow - day * 4,
    userId: "usr_003",
    code: "YIN-MAYA-003",
    createdBy: "admin_002",
    businessId: "biz_studio_atlas",
    name: "Maya Chen",
    profileImageUrl: null,
    email: "maya@example.com",
    phoneNumber: "+1 415 209 7744",
    countryCode: "US",
    address: {
      address: "190 King Street",
      city: "San Francisco",
      state: "California",
      country: "United States",
      postalCode: "94107",
    },
    badge: { badgeId: "silver", points: 2360, updatedAt: contactNow - day * 22 },
    dob: "1988-11-02",
    bmd: "11-02",
    preference: {
      unsubscribedEmailTypes: ["product_updates"],
      smsEnabled: false,
      emailEnabled: true,
      whatsappEnabled: false,
    },
    status: "active",
    lastInteractionAt: contactNow - day * 4,
    anniversary: "2023-10-05",
    tags: ["email only"],
    counts: {
      lifetimeValue: 612000,
      totalOrders: 11,
      messagesSentCount: 16,
      messagesRepliedCount: 7,
    },
    metadata: null,
  },
  {
    id: "ct_004",
    createdAt: contactNow - day * 320,
    updatedAt: contactNow - day * 12,
    userId: "usr_004",
    code: "YIN-DANIEL-004",
    createdBy: "admin_002",
    businessId: "biz_clearpath",
    name: "Daniel Mensah",
    profileImageUrl: null,
    email: "daniel@example.com",
    phoneNumber: "+233 24 778 1091",
    countryCode: "GH",
    address: {
      address: "14 Independence Avenue",
      city: "Accra",
      state: "Greater Accra",
      country: "Ghana",
      postalCode: "GA-184",
    },
    badge: { badgeId: "new", points: 120, updatedAt: contactNow - day * 35 },
    dob: null,
    bmd: null,
    preference: {
      unsubscribedEmailTypes: ["marketing"],
      smsEnabled: false,
      emailEnabled: false,
      whatsappEnabled: true,
    },
    status: "inactive",
    lastInteractionAt: contactNow - day * 12,
    anniversary: null,
    tags: ["at risk"],
    counts: {
      lifetimeValue: 184000,
      totalOrders: 4,
      messagesSentCount: 21,
      messagesRepliedCount: 3,
    },
    metadata: null,
  },
];

export const dummyDiscounts: DiscountData[] = [
  {
    id: "discount_001",
    businessId: "biz_northstar",
    createdAt: Date.now() - day * 14,
    updatedAt: Date.now() - 1000 * 60 * 60 * 5,
    createdBy: "admin_demo",
    title: "Summer Glow 15%",
    description: "Percentage discount for customers buying skincare bundles.",
    type: "discount",
    status: "active",
    code: "GLOW15",
    codeGeneration: "manual",
    reward: {
      maxDiscountAmount: 15000,
      metadata: null,
      type: "percentage_discount",
      value: 15,
    },
    rules: {
      maxUsesPerContact: 2,
      minimumOrderValue: 40000,
      targetBadgeTypes: ["vip"],
      targetTags: ["skin-care", "bundle"],
      totalUsageLimit: 250,
    },
    startsAt: Date.now() - day * 2,
    endsAt: Date.now() + day * 28,
  },
  {
    id: "discount_002",
    businessId: "biz_northstar",
    createdAt: Date.now() - day * 9,
    updatedAt: Date.now() - day,
    createdBy: "admin_demo",
    title: "Launch Weekend Credit",
    description: "Fixed amount off for launch workshop registrations.",
    type: "discount",
    status: "draft",
    code: null,
    codeGeneration: "unique_per_contact",
    reward: {
      metadata: null,
      type: "fixed_amount_discount",
      value: 10000,
    },
    rules: {
      maxUsesPerContact: 1,
      minimumOrderValue: 100000,
      targetBadgeTypes: null,
      targetTags: ["event", "training"],
      totalUsageLimit: 50,
    },
    startsAt: Date.now() + day * 7,
    endsAt: Date.now() + day * 10,
  },
  {
    id: "discount_003",
    businessId: "biz_northstar",
    createdAt: Date.now() - day * 30,
    updatedAt: Date.now() - 1000 * 60 * 60 * 12,
    createdBy: "admin_demo",
    title: "Free Delivery Perk",
    description: "Free shipping for customers tagged as returning buyers.",
    type: "discount",
    status: "paused",
    code: "SHIPFREE",
    codeGeneration: "manual",
    reward: { metadata: null, type: "free_shipping", value: 0 },
    rules: {
      maxUsesPerContact: 3,
      minimumOrderValue: 25000,
      targetBadgeTypes: null,
      targetTags: ["returning"],
      totalUsageLimit: null,
    },
    startsAt: Date.now() - day * 20,
    endsAt: null,
  },
];

export const dummyGifts: GiftData[] = [
  {
    id: "gift_mini_glow_serum",
    businessId: "biz_northstar",
    createdAt: Date.now() - day * 18,
    updatedAt: Date.now() - 1000 * 60 * 60 * 7,
    name: "Mini Glow Serum",
    description: "Travel-size serum for skincare bundle promotions.",
    status: "active",
    estimatedValue: 8500,
    currency: "NGN",
    quantityAvailable: 120,
    maxPerContact: 1,
    imageUrl: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908",
    tags: ["skin-care", "sample"],
  },
  {
    id: "gift_brand_workbook",
    businessId: "biz_northstar",
    createdAt: Date.now() - day * 12,
    updatedAt: Date.now() - day,
    name: "Brand Workbook",
    description: "Digital workbook bundled with consultation discounts.",
    status: "active",
    estimatedValue: 5000,
    currency: "NGN",
    quantityAvailable: null,
    maxPerContact: 1,
    imageUrl: null,
    tags: ["digital", "templates"],
  },
];

export const dummyOfferings: OfferingData[] = [
  {
    id: "offering_001",
    businessId: "biz_northstar",
    createdAt: Date.now() - day * 12,
    updatedAt: Date.now() - 1000 * 60 * 60 * 6,
    name: "Starter Skincare Kit",
    description: "A curated physical kit for first-time customers.",
    type: "product",
    subType: "physical",
    status: "active",
    price: 45000,
    currency: "NGN",
    quantity: 36,
    imageUrls: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03",
      "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b",
    ],
    tags: ["starter", "skin-care", "bundle"],
  },
  {
    id: "offering_002",
    businessId: "biz_northstar",
    createdAt: Date.now() - day * 20,
    updatedAt: Date.now() - day,
    name: "Virtual Brand Consultation",
    description: "A 60 minute advisory session for new business owners.",
    type: "service",
    subType: "consultation_online",
    status: "active",
    price: 30000,
    currency: "NGN",
    duration: 60,
    features: ["booking"],
    imageUrls: ["https://images.unsplash.com/photo-1556761175-b413da4baf72"],
    tags: ["consultation", "virtual"],
    location: null,
    meta: { meetingLink: "https://meet.google.com/example" },
  },
  {
    id: "offering_003",
    businessId: "biz_northstar",
    createdAt: Date.now() - day * 6,
    updatedAt: Date.now() - 1000 * 60 * 30,
    name: "Growth Playbook Download",
    description: "Digital templates and checklists for loyalty launches.",
    type: "product",
    subType: "digital",
    status: "draft",
    price: 15000,
    currency: "NGN",
    quantity: null,
    imageUrls: [],
    tags: ["digital", "templates"],
  },
  {
    id: "offering_004",
    businessId: "biz_northstar",
    createdAt: Date.now() - day * 40,
    updatedAt: Date.now() - 1000 * 60 * 60 * 48,
    name: "In-store Launch Workshop",
    description: "A hands-on event for retail teams adopting Piya.",
    type: "service",
    subType: "event",
    status: "paused",
    price: 120000,
    currency: "NGN",
    duration: 180,
    features: ["booking", "delivery"],
    imageUrls: ["https://images.unsplash.com/photo-1517048676732-d65bc937f952"],
    tags: ["event", "training"],
    location: {
      address: "12 Admiralty Way",
      city: "Lekki",
      state: "Lagos",
      country: "Nigeria",
      postalCode: "105102",
    },
  },
];

export const dummyOrders: OrderData[] = [
  {
    id: "ord_1001",
    shareId: "YIN-1001",
    businessId: "biz_northstar",
    createdAt: orderNow - 1000 * 60 * 52,
    updatedAt: orderNow - 1000 * 60 * 18,
    contact: {
      id: "ct_001",
      name: "Amara Okafor",
      email: "amara@example.com",
      phoneNumber: "+234 801 230 9921",
    },
    status: "fulfilled",
    paymentStatus: "paid",
    currency: "NGN",
    subtotal: 90000,
    total: 95000,
    items: [
      {
        id: "item_1001",
        offeringId: "offering_001",
        name: "Starter Skincare Kit",
        type: "physical",
        quantity: 2,
        unitPrice: 45000,
        fulfillment: {
          address: "18 Admiralty Way",
          city: "Lekki",
          state: "Lagos",
          country: "Nigeria",
          carrier: "GIG Logistics",
          trackingCode: "GIG-829112",
          status: "delivered",
          estimatedDeliveryAt: orderNow + day,
        },
      },
    ],
    notes: "Gift wrap both kits.",
  },
  {
    id: "ord_1002",
    shareId: "YIN-1002",
    businessId: "biz_northstar",
    createdAt: orderNow - 1000 * 60 * 60 * 6,
    updatedAt: orderNow - 1000 * 60 * 60,
    contact: {
      id: "ct_002",
      name: "Tunde Balogun",
      email: "tunde@example.com",
      phoneNumber: "+234 809 441 1820",
    },
    status: "confirmed",
    paymentStatus: "partial",
    currency: "NGN",
    subtotal: 30000,
    total: 30000,
    items: [
      {
        id: "item_1002",
        offeringId: "offering_002",
        name: "Virtual Brand Consultation",
        type: "consultation_online",
        quantity: 1,
        seatCount: 1,
        sessionCount: 1,
        unitPrice: 30000,
        metadata: { durationMinutes: 60 },
      },
    ],
    notes: "Prefers WhatsApp reminder before the session.",
  },
  {
    id: "ord_1003",
    shareId: "YIN-1003",
    businessId: "biz_northstar",
    createdAt: orderNow - 1000 * 60 * 60 * 26,
    updatedAt: orderNow - 1000 * 60 * 60 * 2,
    contact: {
      id: "ct_003",
      name: "Maya Chen",
      email: "maya@example.com",
      phoneNumber: "+1 415 209 7744",
    },
    status: "completed",
    paymentStatus: "paid",
    currency: "USD",
    subtotal: 360,
    total: 360,
    items: [
      {
        id: "item_1003",
        offeringId: "offering_004",
        name: "In-store Launch Workshop",
        type: "event",
        quantity: 1,
        attendeeCount: 3,
        unitPrice: 360,
      },
    ],
  },
  {
    id: "ord_1004",
    shareId: "YIN-1004",
    businessId: "biz_clearpath",
    createdAt: orderNow - 1000 * 60 * 60 * 31,
    updatedAt: orderNow - 1000 * 60 * 12,
    contact: {
      id: "ct_004",
      name: "Daniel Mensah",
      email: "daniel@example.com",
      phoneNumber: "+233 24 778 1091",
    },
    status: "in_progress",
    paymentStatus: "paid",
    currency: "GHS",
    subtotal: 140,
    total: 155,
    items: [
      {
        id: "item_1004",
        name: "Accra same-day dispatch",
        type: "delivery",
        quantity: 1,
        unitPrice: 140,
        fulfillment: {
          address: "14 Independence Avenue",
          city: "Accra",
          state: "Greater Accra",
          country: "Ghana",
          carrier: "QuickMove",
          trackingCode: "QMV-44018",
          status: "in_transit",
          estimatedDeliveryAt: orderNow + 1000 * 60 * 60 * 8,
        },
      },
    ],
  },
  {
    id: "ord_1005",
    shareId: "YIN-1005",
    businessId: "biz_urbanmart",
    createdAt: orderNow - 1000 * 60 * 60 * 46,
    updatedAt: orderNow - 1000 * 60 * 60 * 42,
    contact: {
      id: "ct_005",
      name: "Ifeoma Nwosu",
      email: "ifeoma@example.com",
      phoneNumber: "+234 805 110 4420",
    },
    status: "pending",
    paymentStatus: "unpaid",
    currency: "NGN",
    subtotal: 8500,
    total: 8500,
    items: [
      {
        id: "item_1005",
        name: "Store pickup handling",
        type: "pickup",
        quantity: 1,
        unitPrice: 8500,
        fulfillment: {
          address: "22 Awolowo Road",
          city: "Ikoyi",
          state: "Lagos",
          country: "Nigeria",
          status: "queued",
        },
      },
    ],
  },
];
